name: generic_api_generator
description: generic json api generator
version: 0.0.1
homepage: https://github.com/wenjunxiao/generic_api_generator.dart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  retrofit: ^1.3.4
  tuple: ^1.0.2
  dio: ^3.0.1
  source_gen: ^0.9.4+2
  built_collection: ^4.2.0
  code_builder: ^3.2.0
  dart_style: ^1.3.3
  analyzer: ^0.39.3
  build: ^1.2.2

dev_dependencies:
  test: any
  source_gen_test: any
  mock_web_server: any
  logger: any
  build_runner: any
  generic_json_serializable: ^0.0.1
  generic_json_annotation: ^0.0.1
  json_annotation: ^3.0.1